version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'laravelapp'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:8.0
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'laravel_coding_challenge'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      MYSQL_ROOT_PASSWORD: ""